### ISSUE TITLE
Operaciones basicas_Victor Noe Osorio Sanchez_1AS

### ISSUE THREAD

**Issue by Victor-noe12** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Victor-noe12#1]
[OPERACIONES BASICAS.pdf](https://github.com/user-attachments/files/16845629/OPERACIONES.BASICAS.pdf)

**Comment by Alondra-oss** [comment]
Portada 25/25
Procedimiento 25/25
Figuras, Ilustraciones y fotografías 25/25
Resultados y conclusiones 25/25
Calificacion de la practica: 20

**Comment by Alondra-oss** [comment]
portada 25/25
procedimiento 25/25
figuras, ilustraciones y fotografías 25/25
resultados y conclusiones 25/25
calificacion de la practica : 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
